### PR TITLE
Add some optional serde implementations, as well as .clone on BVH

### PR DESCRIPTION
**Pull request by aidanhs**

### CODE REVIEW

**Comment by svenstaro** [comment]
I'm generally fine with this but make the CI happy. :)

**Comment by aidanhs** [comment]
Looks like nightly just flat-out breaks a dependency deep in the tree (num-bigint)

https://github.com/rust-num/num-bigint/pull/219
https://github.com/rust-lang/rust/issues/88617

I'll wait until num-bigint gets a patch and then prompt CI to rerun.

**Comment by aidanhs** [comment]
> First-time contributors need a maintainer to approve running workflows.

Can you approve? :smile:

**Comment by svenstaro** [comment]
Cool, thanks!

**Comment by aidanhs** [comment]
Thanks for quick merge!

**Pull request merged**
